[tool.poetry]
name = "markovshousehold"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "3.10.4"
Sphinx = "^4.5.0"
myst-parser = "^0.18.0"
sphinx-rtd-theme = "^1.0.0"
pytest = "^7.1.2"
PyYAML = "^6.0"
black = "^22.3.0"
flake8 = "^4.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"