[tool.poetry]
name = "markovshousehold"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "3.10.4"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
flake8-black = "^0.3.3"
Sphinx = "^4.5.0"
myst-parser = "^0.18.0"
sphinx-rtd-theme = "^1.0.0"
pytest = "^7.1.2"
black = "^22.3.0"
flake8 = "^4.0.1"
isort = "^5.10.1"
flake8-isort = "^4.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"