[tool.poetry]
name = "markovshousehold"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "3.10"
Sphinx = "^4.2.0"
myst-parser = "^0.15.2"
sphinx-rtd-theme = "^1.0.0"
pytest = "^7.0.1"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"