@startuml
'https://plantuml.com/activity-diagram-beta

start
:initialize households;
:current_time = start_time
appliance_state_distribution = initial_appliance_state_distribution * nr_appliances;
note left: number of devices in the different stages \n initially all appliances are off (build up)
:assign transition matrix;
note left:

stop

@enduml
