@startuml
(*) --> "Ask user, if load swifting shall be considered"
--> "Read in probabilities"
--> "Set up GUI"
note left: This is more or less a GUI for configuring the whole routine
--> "Define variables"
if "Consider load shifting?" then
    partition "Consider load shifting" {
    -->[true] "Ask user, if to simulate according to typical days"
    if "Consider typical days?" then
        partition "Consider typical days" {
            -->[true] "//goto:// Wahrscheinlichkeiten_Lastverschiebung"
            --> "Prompt main menu"
            note left: 1 = calculate transition probability\n2 = Analytic simulation of load curves\n3 = Plot analytic load curves\n4 = Monte Carlo simulation\n5 = Transfer MC results to xlsx\n9 = Quit
            if "1?" then
                -->[true] "//goto:// Parameterberechnung_nach"
                --> "Prompt main menu"
            else
                if "2?" then
                    -->[true] "//goto:// Simulation_nach"
                    --> "Prompt main menu"
                else
                    if "3?" then
                        -->[true] "//goto:// Plotten_nach"
                        --> "Prompt main menu"
                    else
                        if "4?" then
                            -->[true] "Ask for amount of MC iterations"
                            --> "//goto:// Simulation_Monte_Carlo_nach"
                            --> "Prompt main menu"
                        else
                            if "5?" then
                                -->[true] "//goto:// Monte_Carlo_Excel_Uebertragung"
                                --> "Prompt main menu"
                            else
                                if "9?" then
                                    -->[true] (*)
                                else
                                    --> "Prompt main menu"
                                endif
                            endif
                        endif
                    endif
                endif
            endif
        }
    else
        partition "Don't consider typical days" {
            --> "//goto:// Wahrscheinlichkeiten_Lastverschiebung_Jahr"
            --> "Prompt main menu (2)"
            if "1?" then
                -->[true] "//goto:// Parameterberechnung_nach (2)"
                -->[true] "//goto:// Parameterberechnung_nach_Jahr"
                --> "Prompt main menu (2)"
            else
                if "2?" then
                    -->[true] "//goto:// Simulation_nach (2)"
                    --> "Prompt main menu (2)"
                else
                    if "3?" then
                        -->[true] "//goto:// Plotten_nach (2)"
                        --> "Prompt main menu (2)"
                    else
                        if "4?" then
                            -->[true] "Ask for amount of MC iterations (2)"
                            --> "//goto:// Simulation_Monte_Carlo_nach_Jahr"
                            --> "Prompt main menu (2)"
                        else
                            if "5?" then
                                -->[true] "//goto:// Monte_Carlo_Excel_Uebertragung (2)"
                                --> "Prompt main menu (2)"
                            else
                                if "9?" then
                                    -->[true] (*)
                                else
                                    --> "Prompt main menu (2)"
                                endif
                            endif
                        endif
                    endif
                endif
            endif
        }
    endif
    }
else
    partition "Don't consider load shifting"
    --> "Prompt main menu (3)"
    if "1?" then
        -->[true] "//goto:// Parameterberechnung"
        --> "Prompt main menu (3)"
    else
        if "2?" then
            -->[true] "//goto:// Simulation"
            --> "Prompt main menu (3)"
        else
            if "3?" then
                -->[true] "//goto:// Plotten"
                --> "Prompt main menu (3)"
            else
                if "4?" then
                    -->[true] "Ask for amount of MC iterations (3)"
                    --> "//goto:// Simulation_Monte_Carlo"
                    --> "Prompt main menu (3)"
                else
                    if "5?" then
                        -->[true] "//goto:// Monte_Carlo_Excel_Uebertragung (3)"
                        --> "Prompt main menu (3)"
                    else
                        if "9?" then
                            -->[true] (*)
                        else
                            --> "Prompt main menu (3)"
                        endif
                    endif
                endif
            endif
        endif
    endif
endif
--> (*)
@enduml